[2024-11-11 15:37:14,481: INFO: main: custom logger up and running....] 
[2024-11-11 17:16:14,932: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-11 17:18:32,788: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-11 17:18:32,793: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-11 17:18:32,809: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-11 17:18:32,810: INFO: common: created directory at: artifacts] 
[2024-11-11 17:18:32,814: INFO: common: created directory at: artifacts/data_ingestion] 
[2024-11-11 17:18:33,857: INFO: 251335794: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BF32:365A46:8C693:A243E:6731EF11
Accept-Ranges: bytes
Date: Mon, 11 Nov 2024 11:48:33 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100030-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1731325713.446270,VS0,VE293
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3778e86272098f1ed4be98a6979db46c487387fe
Expires: Mon, 11 Nov 2024 11:53:33 GMT
Source-Age: 0

] 
[2024-11-11 17:42:55,504: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<<] 
[2024-11-11 17:42:55,506: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-11 17:42:55,507: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-11 17:42:55,507: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-11 17:42:55,507: INFO: common: created directory at: artifacts] 
[2024-11-11 17:42:55,508: INFO: common: created directory at: artifacts/data_ingestion] 
[2024-11-11 17:42:56,349: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BF32:365A46:8C693:A243E:6731EF11
Accept-Ranges: bytes
Date: Mon, 11 Nov 2024 12:12:56 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100020-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1731327176.897068,VS0,VE303
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d05f2473f6f6ba079b41fcc083490a646fe6801e
Expires: Mon, 11 Nov 2024 12:17:56 GMT
Source-Age: 0

] 
[2024-11-11 17:42:56,353: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<<] 
[2024-11-12 10:34:37,957: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 10:35:28,897: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 10:35:52,297: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 10:36:04,508: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 10:47:12,934: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 10:47:41,538: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:07:07,960: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:07:07,960: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:07:07,960: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:07:07,960: INFO: common: created directory at: artifacts] 
[2024-11-12 11:07:07,965: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:07:07,972: ERROR: data_validation: Error occurred during data validation: 'dict_keys' object has no attribute 'get'] 
[2024-11-12 11:08:43,936: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:08:43,940: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:08:43,942: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:08:43,942: INFO: common: created directory at: artifacts] 
[2024-11-12 11:08:43,942: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:10:53,546: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:10:53,548: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:10:53,549: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:10:53,549: INFO: common: created directory at: artifacts] 
[2024-11-12 11:10:53,549: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:11:55,533: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:11:55,533: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:11:55,538: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:11:55,538: INFO: common: created directory at: artifacts] 
[2024-11-12 11:11:55,538: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:13:10,375: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:13:10,379: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:13:10,381: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:13:10,381: INFO: common: created directory at: artifacts] 
[2024-11-12 11:13:10,381: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:14:26,351: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:14:26,355: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:14:26,357: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:14:26,357: INFO: common: created directory at: artifacts] 
[2024-11-12 11:14:26,357: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:16:09,538: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:16:09,538: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:16:09,549: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:16:09,549: INFO: common: created directory at: artifacts] 
[2024-11-12 11:16:09,550: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:18:58,617: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:18:58,617: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:18:58,621: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:18:58,621: INFO: common: created directory at: artifacts] 
[2024-11-12 11:18:58,622: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:21:02,838: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:21:02,852: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:21:02,854: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:21:02,856: INFO: common: created directory at: artifacts] 
[2024-11-12 11:21:02,856: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:27:25,969: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 11:27:25,969: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 11:27:25,973: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 11:27:25,974: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 11:27:25,977: INFO: common: created directory at: artifacts] 
[2024-11-12 11:27:25,977: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 11:27:25,998: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 12:19:34,595: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 12:19:34,601: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 12:19:34,601: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 12:19:34,603: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 12:19:34,603: INFO: common: created directory at: artifacts] 
[2024-11-12 12:19:34,603: INFO: common: created directory at: artifacts/data_transformation] 
[2024-11-12 12:19:34,603: ERROR: main: 'DataTransformationConfig' object has no attribute 'data_path'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 28, in <module>
    obj.initiate_data_transformation()
  File "D:\repositories\datascience_project\src\datascience\pipeline\data_transformation_pipeline.py", line 16, in initiate_data_transformation
    data_transformation.train_test_splitting()
  File "D:\repositories\datascience_project\src\datascience\components\data_transformation.py", line 12, in train_test_splitting
    data = pd.read_csv(self.config.data_path)
AttributeError: 'DataTransformationConfig' object has no attribute 'data_path'
[2024-11-12 12:21:17,266: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 12:21:17,270: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 12:21:17,270: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 12:21:17,274: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 12:21:17,274: INFO: common: created directory at: artifacts] 
[2024-11-12 12:21:17,274: INFO: common: created directory at: artifacts/data_transformation] 
[2024-11-12 12:21:17,324: INFO: data_transformation: Splitting data into training and test sets done.] 
[2024-11-12 12:21:17,324: INFO: data_transformation: Shape of train set: (1199, 12)] 
[2024-11-12 12:21:17,324: INFO: data_transformation: Shape of test set: (400, 12)] 
[2024-11-12 12:21:17,324: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 15:30:14,583: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:30:14,594: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:30:14,594: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:30:14,599: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:30:14,600: INFO: common: created directory at: artifacts] 
[2024-11-12 15:30:14,600: ERROR: main: 'function' object has no attribute 'train_data_path'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 15, in initiate_model_training
    model_trainer.train()
  File "D:\repositories\datascience_project\src\datascience\components\model_trainer.py", line 13, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-11-12 15:36:38,994: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:36:39,000: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:36:39,000: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:36:39,000: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:36:39,000: INFO: common: created directory at: artifacts] 
[2024-11-12 15:36:39,000: ERROR: main: 'function' object has no attribute 'keys'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 14, in initiate_model_training
    print(model_training_config.keys())
AttributeError: 'function' object has no attribute 'keys'
[2024-11-12 15:40:37,534: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:40:37,545: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:40:37,545: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:40:37,551: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:40:37,552: INFO: common: created directory at: artifacts] 
[2024-11-12 15:40:37,552: ERROR: main: 'function' object has no attribute 'train_data_path'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 16, in initiate_model_training
    model_trainer.train()
  File "D:\repositories\datascience_project\src\datascience\components\model_trainer.py", line 14, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-11-12 15:43:18,845: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:43:18,861: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:43:18,861: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:43:18,861: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:43:18,861: INFO: common: created directory at: artifacts] 
[2024-11-12 15:43:18,861: ERROR: main: 'function' object has no attribute 'train_data_path'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 16, in initiate_model_training
    model_trainer.train()
  File "D:\repositories\datascience_project\src\datascience\components\model_trainer.py", line 14, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'function' object has no attribute 'train_data_path'
[2024-11-12 15:45:24,544: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:45:24,548: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:45:24,549: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:45:24,551: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:45:24,551: INFO: common: created directory at: artifacts] 
[2024-11-12 15:45:24,551: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:45:24,551: ERROR: main: "'ConfigBox' object has no attribute 'l1_ratio'"] 
Traceback (most recent call last):
  File "box\\box.py", line 593, in box.box.Box.__getitem__
KeyError: 'l1_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 632, in box.box.Box.__getattr__
  File "box\\box.py", line 620, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'l1_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 634, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'l1_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 648, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'l1_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 593, in box.box.Box.__getitem__
KeyError: 'l1_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 632, in box.box.Box.__getattr__
  File "box\\box.py", line 620, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'l1_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 634, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'l1_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 13, in initiate_model_training
    model_training_config = config.get_model_trainer_config()
  File "D:\repositories\datascience_project\src\datascience\config\configuration.py", line 72, in get_model_trainer_config
    l1_ratio= params.l1_ratio,
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 648, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'l1_ratio'"
[2024-11-12 15:46:43,769: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:46:43,779: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:46:43,779: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:46:43,781: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:46:43,781: INFO: common: created directory at: artifacts] 
[2024-11-12 15:46:43,781: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:46:43,781: ERROR: main: ModelTrainerConfig.__init__() got an unexpected keyword argument 'root_dir'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 13, in initiate_model_training
    model_training_config = config.get_model_trainer_config()
  File "D:\repositories\datascience_project\src\datascience\config\configuration.py", line 66, in get_model_trainer_config
    model_tranier_config = ModelTrainerConfig(
TypeError: ModelTrainerConfig.__init__() got an unexpected keyword argument 'root_dir'
[2024-11-12 15:48:00,435: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:48:00,445: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:48:00,445: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:48:00,447: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:48:00,447: INFO: common: created directory at: artifacts] 
[2024-11-12 15:48:00,447: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:48:00,462: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_trasformation/train.csv'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 15, in initiate_model_training
    model_trainer.train()
  File "D:\repositories\datascience_project\src\datascience\components\model_trainer.py", line 13, in train
    train_data = pd.read_csv(self.config.train_data_path)
  File "d:\repositories\datascience_project\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "d:\repositories\datascience_project\venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "d:\repositories\datascience_project\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "d:\repositories\datascience_project\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "d:\repositories\datascience_project\venv\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_trasformation/train.csv'
[2024-11-12 15:50:09,547: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:50:09,554: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:50:09,554: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:50:09,554: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:50:09,554: INFO: common: created directory at: artifacts] 
[2024-11-12 15:50:09,554: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:50:09,601: ERROR: main: 'ModelTrainerConfig' object has no attribute 'rootdir'] 
Traceback (most recent call last):
  File "D:\repositories\datascience_project\main.py", line 38, in <module>
    obj.initiate_model_training()
  File "D:\repositories\datascience_project\src\datascience\pipeline\model_training_pipeline.py", line 15, in initiate_model_training
    model_trainer.train()
  File "D:\repositories\datascience_project\src\datascience\components\model_trainer.py", line 24, in train
    joblib.dump(lr, os.path.join(self.config.rootdir, self.config.model_name))
AttributeError: 'ModelTrainerConfig' object has no attribute 'rootdir'
[2024-11-12 15:51:53,508: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:51:53,516: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:51:53,516: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:51:53,518: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:51:53,518: INFO: common: created directory at: artifacts] 
[2024-11-12 15:51:53,518: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:51:53,551: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 15:56:38,267: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<<] 
[2024-11-12 15:56:38,271: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:56:38,272: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:56:38,274: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:56:38,274: INFO: common: created directory at: artifacts] 
[2024-11-12 15:56:38,289: INFO: common: created directory at: artifacts/data_ingestion] 
[2024-11-12 15:56:39,146: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C981:34B93A:1C67FE:22566F:67332D5E
Accept-Ranges: bytes
Date: Tue, 12 Nov 2024 10:26:39 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100028-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1731407199.158508,VS0,VE312
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3ec565e9e8903ffa2b50866779c7ec83c4d7a827
Expires: Tue, 12 Nov 2024 10:31:39 GMT
Source-Age: 0

] 
[2024-11-12 15:56:39,151: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<<] 
[2024-11-12 15:56:39,151: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:56:39,151: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:56:39,151: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:56:39,156: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:56:39,156: INFO: common: created directory at: artifacts] 
[2024-11-12 15:56:39,156: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 15:56:39,168: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 15:56:39,168: INFO: main: >>>>>>> stage Data Transformation Stage started <<<<<<<<<] 
[2024-11-12 15:56:39,172: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:56:39,173: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:56:39,175: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:56:39,177: INFO: common: created directory at: artifacts] 
[2024-11-12 15:56:39,177: INFO: common: created directory at: artifacts/data_transformation] 
[2024-11-12 15:56:39,201: INFO: data_transformation: Splitting data into training and test sets done.] 
[2024-11-12 15:56:39,201: INFO: data_transformation: Shape of train set: (1199, 12)] 
[2024-11-12 15:56:39,201: INFO: data_transformation: Shape of test set: (400, 12)] 
[2024-11-12 15:56:39,201: INFO: main: >>>>>>> stage Data Transformation Stage completed <<<<<<<<<] 
[2024-11-12 15:56:39,201: INFO: main: >>>>>>> stage Model Training Stage started <<<<<<<<<] 
[2024-11-12 15:56:39,204: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:56:39,206: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:56:39,206: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:56:39,206: INFO: common: created directory at: artifacts] 
[2024-11-12 15:56:39,210: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:56:39,224: INFO: main: >>>>>>> stage Model Training Stage completed <<<<<<<<<] 
[2024-11-12 15:58:29,417: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<<] 
[2024-11-12 15:58:29,419: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:58:29,419: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:58:29,423: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:58:29,423: INFO: common: created directory at: artifacts] 
[2024-11-12 15:58:29,423: INFO: common: created directory at: artifacts/data_ingestion] 
[2024-11-12 15:58:29,423: INFO: data_ingestion: File already exists] 
[2024-11-12 15:58:29,426: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<<] 
[2024-11-12 15:58:29,426: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 15:58:29,429: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:58:29,430: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:58:29,433: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:58:29,433: INFO: common: created directory at: artifacts] 
[2024-11-12 15:58:29,433: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 15:58:29,448: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 15:58:29,448: INFO: main: >>>>>>> stage Data Transformation Stage started <<<<<<<<<] 
[2024-11-12 15:58:29,450: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:58:29,452: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:58:29,455: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:58:29,456: INFO: common: created directory at: artifacts] 
[2024-11-12 15:58:29,456: INFO: common: created directory at: artifacts/data_transformation] 
[2024-11-12 15:58:29,477: INFO: data_transformation: Splitting data into training and test sets done.] 
[2024-11-12 15:58:29,477: INFO: data_transformation: Shape of train set: (1199, 12)] 
[2024-11-12 15:58:29,477: INFO: data_transformation: Shape of test set: (400, 12)] 
[2024-11-12 15:58:29,477: INFO: main: >>>>>>> stage Data Transformation Stage completed <<<<<<<<<] 
[2024-11-12 15:58:29,477: INFO: main: >>>>>>> stage Model Training Stage started <<<<<<<<<] 
[2024-11-12 15:58:29,482: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 15:58:29,482: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 15:58:29,485: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 15:58:29,487: INFO: common: created directory at: artifacts] 
[2024-11-12 15:58:29,487: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 15:58:29,501: INFO: main: >>>>>>> stage Model Training Stage completed <<<<<<<<<] 
[2024-11-12 18:41:18,562: INFO: main: >>>>>>> stage Model Evaluation started <<<<<<<<<] 
[2024-11-12 18:41:18,562: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:41:18,562: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:41:18,562: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:41:18,562: INFO: common: created directory at: artifacts] 
[2024-11-12 18:41:18,562: INFO: common: created directory at: artifacts/model_evaluation] 
[2024-11-12 18:41:20,759: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json] 
[2024-11-12 18:41:30,301: INFO: main: >>>>>>> stage Model Evaluation completed <<<<<<<<<] 
[2024-11-12 18:48:05,881: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<<] 
[2024-11-12 18:48:05,881: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:48:05,881: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:48:05,881: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:48:05,881: INFO: common: created directory at: artifacts] 
[2024-11-12 18:48:05,881: INFO: common: created directory at: artifacts/data_ingestion] 
[2024-11-12 18:48:05,881: INFO: data_ingestion: File already exists] 
[2024-11-12 18:48:05,901: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<<] 
[2024-11-12 18:48:05,901: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<<] 
[2024-11-12 18:48:05,905: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:48:05,905: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:48:05,906: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:48:05,907: INFO: common: created directory at: artifacts] 
[2024-11-12 18:48:05,907: INFO: common: created directory at: artifacts/data_validation] 
[2024-11-12 18:48:05,914: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<<] 
[2024-11-12 18:48:05,914: INFO: main: >>>>>>> stage Data Transformation Stage started <<<<<<<<<] 
[2024-11-12 18:48:05,916: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:48:05,916: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:48:05,916: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:48:05,916: INFO: common: created directory at: artifacts] 
[2024-11-12 18:48:05,916: INFO: common: created directory at: artifacts/data_transformation] 
[2024-11-12 18:48:05,934: INFO: data_transformation: Splitting data into training and test sets done.] 
[2024-11-12 18:48:05,934: INFO: data_transformation: Shape of train set: (1199, 12)] 
[2024-11-12 18:48:05,934: INFO: data_transformation: Shape of test set: (400, 12)] 
[2024-11-12 18:48:05,934: INFO: main: >>>>>>> stage Data Transformation Stage completed <<<<<<<<<] 
[2024-11-12 18:48:05,935: INFO: main: >>>>>>> stage Model Training Stage started <<<<<<<<<] 
[2024-11-12 18:48:05,936: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:48:05,938: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:48:05,938: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:48:05,940: INFO: common: created directory at: artifacts] 
[2024-11-12 18:48:05,941: INFO: common: created directory at: artifacts/model_trainer] 
[2024-11-12 18:48:05,948: INFO: main: >>>>>>> stage Model Training Stage completed <<<<<<<<<] 
[2024-11-12 18:48:05,948: INFO: main: >>>>>>> stage Model Evaluation started <<<<<<<<<] 
[2024-11-12 18:48:05,951: INFO: common: yaml file: config\config.yaml loaded successfully] 
[2024-11-12 18:48:05,951: INFO: common: yaml file: params.yaml loaded successfully] 
[2024-11-12 18:48:05,953: INFO: common: yaml file: schema.yaml loaded successfully] 
[2024-11-12 18:48:05,953: INFO: common: created directory at: artifacts] 
[2024-11-12 18:48:05,953: INFO: common: created directory at: artifacts/model_evaluation] 
[2024-11-12 18:48:06,818: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json] 
[2024-11-12 18:48:17,374: INFO: main: >>>>>>> stage Model Evaluation completed <<<<<<<<<] 
